export const GET_LIST = "GET_LIST";
export const SEND_POST = "SEND_POST";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const SEND_POST_SUCCESS = "SEND_POST_SUCCESS";

export const EDIT_POST = "EDIT_POST";
export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";